/*
Copyright (C) 2019 John Nesky

Permission is hereby granted, free of charge, to any person obtaining a copy of 
this software and associated documentation files (the "Software"), to deal in 
the Software without restriction, including without limitation the rights to 
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies 
of the Software, and to permit persons to whom the Software is furnished to do 
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all 
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
SOFTWARE.
*/

/// <reference path="SynthConfig.ts" />

namespace beepbox {
	export interface PresetCategory extends BeepBoxOption {
		readonly presets: DictionaryArray<Preset>;
	}

	export interface Preset extends BeepBoxOption {
		readonly isNoise?: boolean;
		readonly generalMidi?: boolean;
		readonly midiProgram?: number;
		readonly midiSubharmonicOctaves?: number;
		readonly customType?: InstrumentType;
		//readonly generator?: (i: Instrument)=>void;
		readonly settings?: any;
	}

	export interface ChannelColors extends BeepBoxOption {
		readonly channelDim: string;
		readonly channelBright: string;
		readonly noteDim: string;
		readonly noteBright: string;
	}
	
	export class EditorConfig {
		public static readonly presetCategories: DictionaryArray<PresetCategory> = toNameMap([
			{name: "Custom", presets: <DictionaryArray<Preset>> toNameMap([
				{name: "chip wave",        customType: InstrumentType.chip},
				{name: "FM (expert)",      customType: InstrumentType.fm},
				{name: "chip noise",       customType: InstrumentType.noise},
				{name: "spectrum",         customType: InstrumentType.spectrum},
				{name: "drumset",          customType: InstrumentType.drumset},
				{name: "harmonics",        customType: InstrumentType.harmonics},
			])},
			{name: "Chiptune", presets: <DictionaryArray<Preset>> toNameMap([
				{name: "square wave",      midiProgram:  80, settings: {"type":"chip","transition":"seamless","effects":"none","chord":"arpeggio","filterCutoffHz":4000,"filterResonance":0,"filterEnvelope":"steady","wave":"square","interval":"union","vibrato":"none"}},
				{name: "triangle wave",    midiProgram:  71, settings: {"type":"chip","transition":"seamless","effects":"none","chord":"arpeggio","filterCutoffHz":4000,"filterResonance":0,"filterEnvelope":"steady","wave":"triangle","interval":"union","vibrato":"none"}},
				{name: "square synth",     midiProgram:  80, generalMidi: true, settings: {"type":"chip","transition":"hard","effects":"reverb","chord":"harmony","filterCutoffHz":2828,"filterResonance":14,"filterEnvelope":"steady","wave":"square","interval":"hum","vibrato":"none"}},
				{name: "sawtooth synth",   midiProgram:  81, generalMidi: true, settings: {"type":"chip","transition":"hard","effects":"reverb","chord":"harmony","filterCutoffHz":2828,"filterResonance":14,"filterEnvelope":"steady","wave":"sawtooth","interval":"shimmer","vibrato":"none"}},
			])},
			{name: "Keyboards", presets: <DictionaryArray<Preset>> toNameMap([
				{name: "grand piano",      midiProgram:   0, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"hard fade","chord":"harmony","filterCutoffHz":4000,"filterResonance":29,"filterEnvelope":"twang 3","interval":"shimmer","vibrato":"none","harmonics":[100,86,86,86,86,71,71,57,0,57,29,43,57,57,57,43,43,0,29,43,43,43,43,43,43,29,0,29]}},
				{name: "bright piano",     midiProgram:   1, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"hard fade","chord":"harmony","filterCutoffHz":2828,"filterResonance":29,"filterEnvelope":"twang 3","interval":"shimmer","vibrato":"none","harmonics":[86,100,100,100,86,71,0,86,86,71,71,71,57,0,57,71,57,43,43,43,0,43,43,43,43,43,43,43]}},
				{name: "electric grand",   midiProgram:   2, generalMidi: true, settings: {"type":"chip","effects":"reverb","transition":"hard fade","chord":"harmony","filterCutoffHz":2000,"filterResonance":14,"filterEnvelope":"twang 3","wave":"1/8 pulse","interval":"shimmer","vibrato":"none"}},
				{name: "honky-tonk piano", midiProgram:   3, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"hard fade","chord":"harmony","filterCutoffHz":5657,"filterResonance":29,"filterEnvelope":"twang 2","interval":"honky tonk","vibrato":"none","harmonics":[100,100,86,71,86,71,43,71,43,43,57,57,57,29,57,43,43,43,43,43,29,43,43,43,29,29,29,29]}},
				{name: "electric piano 1", midiProgram:   4, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"hard","chord":"harmony","filterCutoffHz":2828,"filterResonance":14,"filterEnvelope":"twang 2","interval":"union","vibrato":"none","harmonics":[86,100,100,71,71,57,57,43,43,43,29,29,29,14,14,14,0,0,0,0,0,57,0,0,0,0,0,0]}},
				{name: "electric piano 2", midiProgram:   5, generalMidi: true, settings: {"type":"FM","transition":"hard fade","effects":"reverb","chord":"harmony","filterCutoffHz":2828,"filterResonance":0,"filterEnvelope":"twang 3","vibrato":"none","algorithm":"1←3 2←4","feedbackType":"1⟲ 2⟲","feedbackAmplitude":0,"feedbackEnvelope":"steady","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":6,"envelope":"steady"},{"frequency":"1×","amplitude":9,"envelope":"steady"},{"frequency":"16×","amplitude":4,"envelope":"steady"}]}},
				{name: "harpsichord",      midiProgram:   6, generalMidi: true, settings: {"type":"FM","transition":"hard fade","effects":"reverb","chord":"harmony","filterCutoffHz":8000,"filterResonance":14,"filterEnvelope":"twang 3","vibrato":"none","algorithm":"1←(2 3←4)","feedbackType":"3⟲","feedbackAmplitude":5,"feedbackEnvelope":"steady","operators":[{"frequency":"2×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":7,"envelope":"steady"},{"frequency":"5×","amplitude":5,"envelope":"steady"},{"frequency":"1×","amplitude":14,"envelope":"steady"}]}},
				{name: "clavinet",         midiProgram:   7, generalMidi: true, settings: {"type":"FM","transition":"hard","effects":"reverb","chord":"harmony","filterCutoffHz":5657,"filterResonance":0,"filterEnvelope":"twang 2","vibrato":"none","algorithm":"1←(2 3 4)","feedbackType":"3⟲","feedbackAmplitude":6,"feedbackEnvelope":"twang 2","operators":[{"frequency":"3×","amplitude":15,"envelope":"custom"},{"frequency":"~1×","amplitude":6,"envelope":"steady"},{"frequency":"8×","amplitude":4,"envelope":"steady"},{"frequency":"1×","amplitude":0,"envelope":"steady"}]}},
				{name: "dulcimer",         midiProgram:  15, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"hard fade","chord":"strum","filterCutoffHz":5657,"filterResonance":14,"filterEnvelope":"twang 2","interval":"shimmer","vibrato":"none","harmonics":[86,86,86,71,86,71,43,86,86,71,100,71,100,71,86,57,43,57,57,86,71,57,71,71,86,71,71,71]}},
			])},
			{name: "Idiophones", presets: <DictionaryArray<Preset>> toNameMap([
				{name: "celesta",          midiProgram:   8, generalMidi: true, settings: {"type":"FM","transition":"hard fade","effects":"reverb","chord":"strum","filterCutoffHz":5657,"filterResonance":14,"filterEnvelope":"twang 2","vibrato":"none","algorithm":"(1 2)←(3 4)","feedbackType":"1⟲ 2⟲","feedbackAmplitude":0,"feedbackEnvelope":"steady","operators":[{"frequency":"~1×","amplitude":15,"envelope":"custom"},{"frequency":"8×","amplitude":7,"envelope":"custom"},{"frequency":"20×","amplitude":3,"envelope":"twang 1"},{"frequency":"3×","amplitude":1,"envelope":"twang 2"}]}},
				{name: "glockenspiel",     midiProgram:   9, generalMidi: true, settings: {"type":"FM","transition":"hard fade","effects":"reverb","chord":"strum","filterCutoffHz":5657,"filterResonance":14,"filterEnvelope":"twang 2","vibrato":"none","algorithm":"(1 2 3)←4","feedbackType":"1⟲ 2⟲ 3⟲","feedbackAmplitude":2,"feedbackEnvelope":"decay 1","operators":[{"frequency":"1×","amplitude":9,"envelope":"custom"},{"frequency":"5×","amplitude":14,"envelope":"custom"},{"frequency":"8×","amplitude":9,"envelope":"custom"},{"frequency":"20×","amplitude":2,"envelope":"twang 1"}]}},
				{name: "music box",        midiProgram:  10, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"hard fade","chord":"strum","filterCutoffHz":4000,"filterResonance":14,"filterEnvelope":"twang 2","interval":"union","vibrato":"none","harmonics":[100,0,0,100,0,0,0,0,0,0,100,0,0,0,0,0,0,0,0,86,0,0,0,0,0,0,71,0]}},
				{name: "vibraphone",       midiProgram:  11, generalMidi: true, settings: {"type":"FM","transition":"hard fade","effects":"reverb","chord":"harmony","filterCutoffHz":2828,"filterResonance":14,"filterEnvelope":"twang 2","vibrato":"none","algorithm":"1 2 3 4","feedbackType":"4⟲","feedbackAmplitude":3,"feedbackEnvelope":"twang 1","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"~1×","amplitude":15,"envelope":"custom"},{"frequency":"9×","amplitude":6,"envelope":"custom"},{"frequency":"4×","amplitude":15,"envelope":"custom"}]}},
				{name: "marimba",          midiProgram:  12, generalMidi: true, settings: {"type":"FM","transition":"hard fade","effects":"reverb","chord":"strum","filterCutoffHz":2000,"filterResonance":29,"filterEnvelope":"decay 1","vibrato":"none","algorithm":"1 2←(3 4)","feedbackType":"3⟲","feedbackAmplitude":0,"feedbackEnvelope":"steady","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"4×","amplitude":10,"envelope":"custom"},{"frequency":"13×","amplitude":6,"envelope":"twang 1"},{"frequency":"1×","amplitude":0,"envelope":"steady"}]}},
				{name: "xylophone",        midiProgram:  13, generalMidi: true, settings: {"type":"FM","transition":"hard","effects":"reverb","chord":"strum","filterCutoffHz":2000,"filterResonance":14,"filterEnvelope":"twang 1","vibrato":"none","algorithm":"(1 2 3)←4","feedbackType":"1⟲ 2⟲ 3⟲","feedbackAmplitude":0,"feedbackEnvelope":"steady","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"6×","amplitude":15,"envelope":"custom"},{"frequency":"11×","amplitude":15,"envelope":"custom"},{"frequency":"20×","amplitude":6,"envelope":"twang 1"}]}},
				{name: "tubular bell",     midiProgram:  14, midiSubharmonicOctaves: 1, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"hard fade","chord":"strum","filterCutoffHz":2000,"filterResonance":14,"filterEnvelope":"twang 3","interval":"hum","vibrato":"none","harmonics":[57,57,0,100,0,100,0,86,0,71,0,0,57,0,0,43,0,0,0,29,0,0,0,14,0,0,0,0]}},
				{name: "rain drop",        midiProgram:  96, generalMidi: true, settings: {"type":"FM","transition":"hard fade","effects":"reverb","chord":"strum","filterCutoffHz":4000,"filterResonance":14,"filterEnvelope":"twang 1","vibrato":"none","algorithm":"(1 2)←(3 4)","feedbackType":"1⟲ 2⟲","feedbackAmplitude":0,"feedbackEnvelope":"steady","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"6×","amplitude":5,"envelope":"custom"},{"frequency":"20×","amplitude":3,"envelope":"twang 1"},{"frequency":"1×","amplitude":6,"envelope":"tremolo1"}]}},
				{name: "crystal",          midiProgram:  98, generalMidi: true, settings: {"type":"FM","transition":"hard fade","effects":"reverb","chord":"harmony","filterCutoffHz":2828,"filterResonance":14,"filterEnvelope":"twang 2","vibrato":"delayed","algorithm":"1 2 3 4","feedbackType":"1⟲ 2⟲ 3⟲ 4⟲","feedbackAmplitude":4,"feedbackEnvelope":"twang 1","operators":[{"frequency":"1×","amplitude":8,"envelope":"custom"},{"frequency":"3×","amplitude":6,"envelope":"custom"},{"frequency":"6×","amplitude":3,"envelope":"custom"},{"frequency":"13×","amplitude":3,"envelope":"custom"}]}},
				{name: "tinkle bell",      midiProgram: 112, generalMidi: true, settings: {"type":"FM","transition":"hard","effects":"reverb","chord":"strum","filterCutoffHz":2828,"filterResonance":14,"filterEnvelope":"twang 2","vibrato":"none","algorithm":"1 2 3 4","feedbackType":"1→2→3→4","feedbackAmplitude":5,"feedbackEnvelope":"twang 3","operators":[{"frequency":"~2×","amplitude":5,"envelope":"custom"},{"frequency":"5×","amplitude":5,"envelope":"custom"},{"frequency":"7×","amplitude":5,"envelope":"custom"},{"frequency":"16×","amplitude":5,"envelope":"custom"}]}},
				{name: "agogo",            midiProgram: 113, generalMidi: true, settings: {"type":"FM","transition":"hard fade","effects":"reverb","chord":"strum","filterCutoffHz":4000,"filterResonance":14,"filterEnvelope":"decay 1","vibrato":"none","algorithm":"1 2 3 4","feedbackType":"1→4","feedbackAmplitude":15,"feedbackEnvelope":"decay 1","operators":[{"frequency":"2×","amplitude":7,"envelope":"custom"},{"frequency":"5×","amplitude":5,"envelope":"custom"},{"frequency":"8×","amplitude":7,"envelope":"custom"},{"frequency":"13×","amplitude":9,"envelope":"custom"}]}},
				{name: "kalimba",          midiProgram: 108, generalMidi: true, settings: {"type":"FM","transition":"hard fade","effects":"reverb","chord":"strum","filterCutoffHz":2828,"filterResonance":14,"filterEnvelope":"decay 1","vibrato":"none","algorithm":"1←(2 3 4)","feedbackType":"1⟲","feedbackAmplitude":0,"feedbackEnvelope":"steady","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"5×","amplitude":3,"envelope":"twang 2"},{"frequency":"20×","amplitude":3,"envelope":"twang 1"},{"frequency":"1×","amplitude":0,"envelope":"steady"}]}},
			])},
			{name: "Picked", presets: <DictionaryArray<Preset>> toNameMap([
				{name: "nylon guitar",     midiProgram:  24, generalMidi: true, settings: {"type":"FM","effects":"reverb","transition":"hard fade","chord":"strum","filterCutoffHz":5657,"filterResonance":14,"filterEnvelope":"twang 1","vibrato":"none","algorithm":"1←2←3←4","feedbackType":"3⟲","feedbackAmplitude":6,"feedbackEnvelope":"twang 1","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":6,"envelope":"steady"},{"frequency":"5×","amplitude":2,"envelope":"steady"},{"frequency":"7×","amplitude":4,"envelope":"steady"}]}},
				{name: "steel guitar",     midiProgram:  25, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"hard fade","chord":"strum","filterCutoffHz":5657,"filterResonance":14,"filterEnvelope":"twang 2","interval":"union","vibrato":"none","harmonics":[100,100,86,71,71,71,86,86,71,57,43,43,43,57,57,57,57,57,43,43,43,43,43,43,43,43,43,43]}},
				{name: "jazz guitar",      midiProgram:  26, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"hard","chord":"strum","filterCutoffHz":2000,"filterResonance":14,"filterEnvelope":"twang 2","interval":"union","vibrato":"none","harmonics":[100,100,86,71,57,71,71,43,57,71,57,43,29,29,29,29,29,29,29,29,14,14,14,14,14,14,14,0]}},
				{name: "clean guitar",     midiProgram:  27, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"hard","chord":"strum","filterCutoffHz":2828,"filterResonance":14,"filterEnvelope":"twang 2","interval":"union","vibrato":"none","harmonics":[86,100,100,100,86,57,86,100,100,100,71,57,43,71,86,71,57,57,71,71,71,71,57,57,57,57,57,43]}},
				{name: "muted guitar",     midiProgram:  28, generalMidi: true, settings: {"type":"FM","transition":"hard","effects":"reverb","chord":"strum","filterCutoffHz":2000,"filterResonance":14,"filterEnvelope":"twang 1","vibrato":"none","algorithm":"1←(2 3←4)","feedbackType":"1⟲","feedbackAmplitude":7,"feedbackEnvelope":"twang 2","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":4,"envelope":"twang 3"},{"frequency":"4×","amplitude":4,"envelope":"twang 2"},{"frequency":"16×","amplitude":4,"envelope":"twang 1"}]}},
				{name: "pizzicato strings",midiProgram:  45, generalMidi: true, settings: {"type":"FM","transition":"medium fade","effects":"reverb","chord":"harmony","filterCutoffHz":2000,"filterResonance":14,"filterEnvelope":"twang 1","vibrato":"none","algorithm":"(1 2 3)←4","feedbackType":"1⟲ 2⟲ 3⟲ 4⟲","feedbackAmplitude":7,"feedbackEnvelope":"twang 1","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"3×","amplitude":12,"envelope":"custom"},{"frequency":"6×","amplitude":10,"envelope":"custom"},{"frequency":"~1×","amplitude":10,"envelope":"steady"}]}},
				{name: "harp",             midiProgram:  46, generalMidi: true, settings: {"type":"FM","transition":"hard fade","effects":"reverb","chord":"strum","filterCutoffHz":2828,"filterResonance":0,"filterEnvelope":"twang 1","vibrato":"none","algorithm":"1←3 2←4","feedbackType":"3⟲","feedbackAmplitude":6,"feedbackEnvelope":"twang 2","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"4×","amplitude":6,"envelope":"custom"},{"frequency":"~2×","amplitude":3,"envelope":"steady"},{"frequency":"1×","amplitude":6,"envelope":"steady"}]}},
				{name: "sitar",            midiProgram: 104, generalMidi: true, settings: {"type":"FM","transition":"hard fade","effects":"reverb","chord":"strum","filterCutoffHz":8000,"filterResonance":57,"filterEnvelope":"twang 2","vibrato":"none","algorithm":"1←(2 3 4)","feedbackType":"1⟲","feedbackAmplitude":0,"feedbackEnvelope":"steady","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":14,"envelope":"twang 3"},{"frequency":"9×","amplitude":3,"envelope":"twang 3"},{"frequency":"16×","amplitude":9,"envelope":"swell 3"}]}},
				{name: "banjo",            midiProgram: 105, generalMidi: true, settings: {"type":"FM","transition":"hard fade","effects":"reverb","chord":"strum","filterCutoffHz":2828,"filterResonance":14,"filterEnvelope":"twang 2","vibrato":"none","algorithm":"1←(2 3←4)","feedbackType":"2⟲","feedbackAmplitude":4,"feedbackEnvelope":"steady","operators":[{"frequency":"4×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":10,"envelope":"steady"},{"frequency":"11×","amplitude":3,"envelope":"twang 3"},{"frequency":"1×","amplitude":11,"envelope":"steady"}]}},
				{name: "shamisen",         midiProgram: 106, generalMidi: true, settings: {"type":"FM","transition":"hard fade","effects":"reverb","chord":"harmony","filterCutoffHz":8000,"filterResonance":14,"filterEnvelope":"twang 1","vibrato":"none","algorithm":"1←(2 3←4)","feedbackType":"3⟲","feedbackAmplitude":15,"feedbackEnvelope":"twang 3","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":12,"envelope":"steady"},{"frequency":"16×","amplitude":4,"envelope":"twang 3"},{"frequency":"1×","amplitude":12,"envelope":"steady"}]}},
				{name: "koto",             midiProgram: 107, generalMidi: true, settings: {"type":"FM","transition":"hard fade","effects":"reverb","chord":"harmony","filterCutoffHz":4000,"filterResonance":14,"filterEnvelope":"twang 2","vibrato":"none","algorithm":"1←3 2←4","feedbackType":"1⟲ 2⟲","feedbackAmplitude":9,"feedbackEnvelope":"twang 2","operators":[{"frequency":"~1×","amplitude":15,"envelope":"custom"},{"frequency":"6×","amplitude":13,"envelope":"custom"},{"frequency":"4×","amplitude":8,"envelope":"twang 3"},{"frequency":"~2×","amplitude":8,"envelope":"twang 3"}]}},
				
				// ukulele!
			])},
			{name: "Picked Basses", presets: <DictionaryArray<Preset>> toNameMap([
				{name: "acoustic bass",    midiProgram:  32, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"hard fade","chord":"strum","filterCutoffHz":4000,"filterResonance":14,"filterEnvelope":"twang 1","interval":"union","vibrato":"none","harmonics":[100,86,71,71,71,71,57,57,57,57,43,43,43,43,43,29,29,29,29,29,29,14,14,14,14,14,14,14]}},
				{name: "fingered bass",    midiProgram:  33, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"hard fade","chord":"strum","filterCutoffHz":2828,"filterResonance":14,"filterEnvelope":"twang 1","interval":"union","vibrato":"none","harmonics":[100,86,71,57,71,43,57,29,29,29,29,29,29,14,14,14,14,14,14,14,14,14,14,14,14,14,14,0]}},
				{name: "picked bass",      midiProgram:  34, generalMidi: true, settings: {"type":"FM","effects":"reverb","transition":"hard fade","chord":"strum","filterCutoffHz":2828,"filterResonance":0,"filterEnvelope":"twang 1","vibrato":"none","algorithm":"1←(2 3←4)","feedbackType":"3⟲","feedbackAmplitude":4,"feedbackEnvelope":"twang 1","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":5,"envelope":"steady"},{"frequency":"11×","amplitude":1,"envelope":"twang 3"},{"frequency":"1×","amplitude":9,"envelope":"steady"}]}},
				{name: "fretless bass",    midiProgram:  35, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"hard","chord":"strum","filterCutoffHz":2828,"filterResonance":14,"filterEnvelope":"flare 2","interval":"union","vibrato":"none","harmonics":[100,100,86,71,71,57,57,71,71,71,57,57,57,57,57,57,57,43,43,43,43,43,43,43,43,29,29,14]}},
				{name: "slap bass 1",      midiProgram:  36, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"hard","chord":"strum","filterCutoffHz":4000,"filterResonance":0,"filterEnvelope":"twang 1","interval":"union","vibrato":"none","harmonics":[100,100,100,100,86,71,57,29,29,43,43,57,71,57,29,29,43,57,57,57,43,43,43,57,71,71,71,71]}},
				{name: "slap bass 2",      midiProgram:  37, generalMidi: true, settings: {"type":"FM","effects":"reverb","transition":"hard","chord":"strum","filterCutoffHz":5657,"filterResonance":0,"filterEnvelope":"twang 1","vibrato":"none","algorithm":"1←2←3←4","feedbackType":"3⟲","feedbackAmplitude":4,"feedbackEnvelope":"steady","operators":[{"frequency":"3×","amplitude":13,"envelope":"custom"},{"frequency":"1×","amplitude":7,"envelope":"steady"},{"frequency":"13×","amplitude":3,"envelope":"steady"},{"frequency":"1×","amplitude":11,"envelope":"steady"}]}},
				{name: "synth bass 1",     midiProgram:  38, generalMidi: true, settings: {"type":"FM","effects":"reverb","transition":"hard","chord":"strum","filterCutoffHz":4000,"filterResonance":43,"filterEnvelope":"twang 2","vibrato":"none","algorithm":"1←3 2←4","feedbackType":"3⟲ 4⟲","feedbackAmplitude":9,"feedbackEnvelope":"twang 2","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":10,"envelope":"custom"},{"frequency":"1×","amplitude":14,"envelope":"twang 1"},{"frequency":"~1×","amplitude":13,"envelope":"twang 2"}]}},
				{name: "synth bass 2",     midiProgram:  39, generalMidi: true, settings: {"type":"FM","effects":"reverb","transition":"hard fade","chord":"strum","filterCutoffHz":1000,"filterResonance":57,"filterEnvelope":"punch","vibrato":"none","algorithm":"1←(2 3 4)","feedbackType":"1→2","feedbackAmplitude":4,"feedbackEnvelope":"twang 3","operators":[{"frequency":"1×","amplitude":11,"envelope":"custom"},{"frequency":"1×","amplitude":9,"envelope":"steady"},{"frequency":"3×","amplitude":0,"envelope":"steady"},{"frequency":"1×","amplitude":0,"envelope":"steady"}]}},
				{name: "bass & lead",      midiProgram:  87, generalMidi: true, settings: {"type":"chip","transition":"hard","effects":"reverb","chord":"harmony","filterCutoffHz":4000,"filterResonance":86,"filterEnvelope":"twang 2","wave":"sawtooth","interval":"shimmer","vibrato":"none"}},
			])},
			{name: "Distortion", presets: <DictionaryArray<Preset>> toNameMap([
				{name: "overdrive guitar", midiProgram:  29, generalMidi: true, settings: {"type":"FM","effects":"reverb","transition":"hard","chord":"harmony","filterCutoffHz":2828,"filterResonance":14,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←(2 3←4)","feedbackType":"1→2","feedbackAmplitude":2,"feedbackEnvelope":"steady","operators":[{"frequency":"~1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":12,"envelope":"steady"},{"frequency":"1×","amplitude":7,"envelope":"twang 3"},{"frequency":"1×","amplitude":4,"envelope":"swell 3"}]}},
				{name: "distortion guitar",midiProgram:  30, generalMidi: true, settings: {"type":"FM","effects":"reverb","transition":"hard","chord":"harmony","filterCutoffHz":2828,"filterResonance":57,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←(2 3←4)","feedbackType":"1→2","feedbackAmplitude":4,"feedbackEnvelope":"steady","operators":[{"frequency":"~1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":11,"envelope":"steady"},{"frequency":"1×","amplitude":9,"envelope":"swell 1"},{"frequency":"~2×","amplitude":5,"envelope":"swell 3"}]}},
				{name: "charango synth",   midiProgram:  84, generalMidi: true, settings: {"type":"FM","effects":"reverb","transition":"hard","chord":"harmony","filterCutoffHz":5657,"filterResonance":0,"filterEnvelope":"twang 3","vibrato":"none","algorithm":"1←(2 3←4)","feedbackType":"1→2→3→4","feedbackAmplitude":8,"feedbackEnvelope":"twang 3","operators":[{"frequency":"3×","amplitude":12,"envelope":"custom"},{"frequency":"~1×","amplitude":5,"envelope":"steady"},{"frequency":"4×","amplitude":6,"envelope":"steady"},{"frequency":"3×","amplitude":7,"envelope":"steady"}]}},
				{name: "guitar harmonics", midiProgram:  31, generalMidi: true, settings: {"type":"FM","transition":"hard","effects":"reverb","chord":"harmony","filterCutoffHz":2000,"filterResonance":29,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←(2 3)←4","feedbackType":"1⟲","feedbackAmplitude":2,"feedbackEnvelope":"steady","operators":[{"frequency":"4×","amplitude":11,"envelope":"custom"},{"frequency":"16×","amplitude":5,"envelope":"swell 1"},{"frequency":"1×","amplitude":2,"envelope":"punch"},{"frequency":"~1×","amplitude":12,"envelope":"twang 1"}]}},
			])},
			{name: "Bellows", presets: <DictionaryArray<Preset>> toNameMap([
				{name: "drawbar organ",    midiProgram:  16, midiSubharmonicOctaves: 1, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"hard","chord":"harmony","filterCutoffHz":2828,"filterResonance":14,"filterEnvelope":"steady","interval":"union","vibrato":"none","harmonics":[86,86,0,86,0,0,0,86,0,0,0,0,0,0,0,86,0,0,0,0,0,0,0,0,0,0,0,0]}},
				{name: "percussive organ", midiProgram:  17, midiSubharmonicOctaves: 1, generalMidi: true, settings: {"type":"FM","transition":"hard","effects":"reverb","chord":"harmony","filterCutoffHz":2000,"filterResonance":14,"filterEnvelope":"punch","vibrato":"light","algorithm":"1 2 3 4","feedbackType":"1→3 2→4","feedbackAmplitude":7,"feedbackEnvelope":"decay 1","operators":[{"frequency":"1×","amplitude":7,"envelope":"custom"},{"frequency":"2×","amplitude":7,"envelope":"custom"},{"frequency":"3×","amplitude":8,"envelope":"custom"},{"frequency":"4×","amplitude":8,"envelope":"custom"}]}},
				{name: "rock organ",       midiProgram:  18, midiSubharmonicOctaves: 1, generalMidi: true, settings: {"type":"FM","transition":"hard","effects":"chorus & reverb","chord":"harmony","filterCutoffHz":5657,"filterResonance":14,"filterEnvelope":"punch","vibrato":"delayed","algorithm":"(1 2 3)←4","feedbackType":"1⟲ 2⟲ 3⟲","feedbackAmplitude":2,"feedbackEnvelope":"flare 1","operators":[{"frequency":"1×","amplitude":11,"envelope":"custom"},{"frequency":"4×","amplitude":11,"envelope":"custom"},{"frequency":"6×","amplitude":11,"envelope":"custom"},{"frequency":"2×","amplitude":5,"envelope":"steady"}]}},
				{name: "pipe organ",       midiProgram:  19, midiSubharmonicOctaves: 1, generalMidi: true, settings: {"type":"FM","transition":"cross fade","effects":"reverb","chord":"harmony","filterCutoffHz":5657,"filterResonance":43,"filterEnvelope":"steady","vibrato":"none","algorithm":"1 2 3 4","feedbackType":"1⟲ 2⟲ 3⟲ 4⟲","feedbackAmplitude":5,"feedbackEnvelope":"steady","operators":[{"frequency":"1×","amplitude":8,"envelope":"custom"},{"frequency":"2×","amplitude":9,"envelope":"custom"},{"frequency":"4×","amplitude":9,"envelope":"custom"},{"frequency":"8×","amplitude":8,"envelope":"custom"}]}},
				{name: "reed organ",       midiProgram:  20, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"soft","chord":"harmony","filterCutoffHz":2000,"filterResonance":29,"filterEnvelope":"steady","interval":"union","vibrato":"none","harmonics":[71,86,100,86,71,100,57,71,71,71,43,43,43,71,43,71,57,57,57,57,57,57,57,29,43,29,29,14]}},
				{name: "accordion",        midiProgram:  21, generalMidi: true, settings: {"type":"chip","transition":"cross fade","effects":"reverb","chord":"harmony","filterCutoffHz":5657,"filterResonance":29,"filterEnvelope":"swell 1","wave":"double saw","interval":"honky tonk","vibrato":"none"}},
				{name: "harmonica",        midiProgram:  22, generalMidi: true, settings: {"type":"FM","transition":"soft","effects":"reverb","chord":"harmony","filterCutoffHz":5657,"filterResonance":29,"filterEnvelope":"swell 1","vibrato":"none","algorithm":"1←(2 3←4)","feedbackType":"1⟲","feedbackAmplitude":9,"feedbackEnvelope":"tremolo5","operators":[{"frequency":"2×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":15,"envelope":"steady"},{"frequency":"~2×","amplitude":2,"envelope":"twang 3"},{"frequency":"1×","amplitude":0,"envelope":"steady"}]}},
				{name: "bandoneon",        midiProgram:  23, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"soft","chord":"harmony","filterCutoffHz":4000,"filterResonance":29,"filterEnvelope":"swell 1","interval":"hum","vibrato":"none","harmonics":[86,86,86,57,71,86,57,71,71,71,57,43,57,43,71,43,71,57,57,43,43,43,57,43,43,29,29,29]}},
				{name: "bagpipe",          midiProgram: 109, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"cross fade","chord":"harmony","filterCutoffHz":5657,"filterResonance":43,"filterEnvelope":"punch","interval":"hum","vibrato":"none","harmonics":[71,86,86,100,100,86,57,100,86,71,71,71,57,57,57,71,57,71,57,71,43,57,57,43,43,43,43,43]}},
			])},
			{name: "Strings", presets: <DictionaryArray<Preset>> toNameMap([
				{name: "violin",           midiProgram:  40, generalMidi: true, settings: {"type":"FM","effects":"reverb","transition":"cross fade","chord":"harmony","filterCutoffHz":2828,"filterResonance":29,"filterEnvelope":"steady","vibrato":"delayed","algorithm":"(1 2 3)←4","feedbackType":"1⟲ 2⟲ 3⟲","feedbackAmplitude":6,"feedbackEnvelope":"swell 1","operators":[{"frequency":"2×","amplitude":13,"envelope":"custom"},{"frequency":"6×","amplitude":10,"envelope":"custom"},{"frequency":"11×","amplitude":6,"envelope":"steady"},{"frequency":"1×","amplitude":6,"envelope":"steady"}]}},
				{name: "viola",            midiProgram:  41, generalMidi: true, settings: {"type":"FM","effects":"reverb","transition":"cross fade","chord":"harmony","filterCutoffHz":2000,"filterResonance":29,"filterEnvelope":"steady","vibrato":"delayed","algorithm":"(1 2 3)←4","feedbackType":"1⟲ 2⟲ 3⟲","feedbackAmplitude":8,"feedbackEnvelope":"swell 1","operators":[{"frequency":"2×","amplitude":15,"envelope":"custom"},{"frequency":"7×","amplitude":10,"envelope":"custom"},{"frequency":"13×","amplitude":6,"envelope":"steady"},{"frequency":"1×","amplitude":5,"envelope":"steady"}]}},
				{name: "cello",            midiProgram:  42, generalMidi: true, settings: {"type":"FM","effects":"reverb","transition":"cross fade","chord":"harmony","filterCutoffHz":2828,"filterResonance":29,"filterEnvelope":"steady","vibrato":"delayed","algorithm":"(1 2 3)←4","feedbackType":"1⟲ 2⟲ 3⟲","feedbackAmplitude":9,"feedbackEnvelope":"swell 1","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"3×","amplitude":12,"envelope":"custom"},{"frequency":"8×","amplitude":8,"envelope":"steady"},{"frequency":"1×","amplitude":4,"envelope":"steady"}]}},
				{name: "contrabass",       midiProgram:  43, generalMidi: true, settings: {"type":"FM","transition":"cross fade","effects":"reverb","chord":"harmony","filterCutoffHz":2000,"filterResonance":29,"filterEnvelope":"steady","vibrato":"delayed","algorithm":"(1 2)←3←4","feedbackType":"1⟲ 2⟲","feedbackAmplitude":0,"feedbackEnvelope":"steady","operators":[{"frequency":"16×","amplitude":7,"envelope":"custom"},{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":10,"envelope":"steady"},{"frequency":"6×","amplitude":3,"envelope":"swell 1"}]}},
				{name: "tremolo strings",  midiProgram:  44, generalMidi: true, settings: {"type":"FM","effects":"chorus & reverb","transition":"medium fade","chord":"harmony","filterCutoffHz":2000,"filterResonance":0,"filterEnvelope":"tremolo4","vibrato":"none","algorithm":"(1 2)←(3 4)","feedbackType":"4⟲","feedbackAmplitude":7,"feedbackEnvelope":"steady","operators":[{"frequency":"4×","amplitude":12,"envelope":"custom"},{"frequency":"3×","amplitude":12,"envelope":"custom"},{"frequency":"2×","amplitude":7,"envelope":"steady"},{"frequency":"7×","amplitude":3,"envelope":"steady"}]}},
				{name: "strings",          midiProgram:  48, generalMidi: true, settings: {"type":"FM","transition":"cross fade","effects":"chorus & reverb","chord":"harmony","filterCutoffHz":2828,"filterResonance":43,"filterEnvelope":"steady","vibrato":"none","algorithm":"(1 2)←(3 4)","feedbackType":"4⟲","feedbackAmplitude":5,"feedbackEnvelope":"twang 3","operators":[{"frequency":"4×","amplitude":12,"envelope":"custom"},{"frequency":"3×","amplitude":12,"envelope":"custom"},{"frequency":"2×","amplitude":7,"envelope":"steady"},{"frequency":"7×","amplitude":3,"envelope":"swell 1"}]}},
				{name: "slow strings",     midiProgram:  49, generalMidi: true, settings: {"type":"FM","transition":"soft fade","effects":"chorus & reverb","chord":"harmony","filterCutoffHz":1414,"filterResonance":0,"filterEnvelope":"swell 3","vibrato":"none","algorithm":"(1 2)←(3 4)","feedbackType":"4⟲","feedbackAmplitude":6,"feedbackEnvelope":"flare 3","operators":[{"frequency":"4×","amplitude":13,"envelope":"custom"},{"frequency":"3×","amplitude":13,"envelope":"custom"},{"frequency":"2×","amplitude":7,"envelope":"steady"},{"frequency":"7×","amplitude":3,"envelope":"swell 1"}]}},
				{name: "synth strings 1",  midiProgram:  50, generalMidi: true, settings: {"type":"chip","volume":60,"transition":"soft fade","effects":"chorus & reverb","chord":"harmony","filterCutoffHz":1414,"filterResonance":43,"filterEnvelope":"steady","wave":"sawtooth","interval":"hum","vibrato":"delayed"}},
				{name: "synth strings 2",  midiProgram:  51, generalMidi: true, settings: {"type":"FM","transition":"soft fade","effects":"chorus & reverb","chord":"harmony","filterCutoffHz":1000,"filterResonance":43,"filterEnvelope":"steady","vibrato":"none","algorithm":"(1 2)←(3 4)","feedbackType":"1⟲ 2⟲","feedbackAmplitude":11,"feedbackEnvelope":"flare 2","operators":[{"frequency":"1×","amplitude":14,"envelope":"custom"},{"frequency":"4×","amplitude":12,"envelope":"custom"},{"frequency":"1×","amplitude":11,"envelope":"steady"},{"frequency":"6×","amplitude":4,"envelope":"steady"}]}},
				{name: "orchestra hit",    midiProgram:  55, midiSubharmonicOctaves: 1, generalMidi: true, settings: {"type":"FM","effects":"chorus & reverb","transition":"medium fade","chord":"harmony","filterCutoffHz":8000,"filterResonance":0,"filterEnvelope":"decay 1","vibrato":"delayed","algorithm":"1 2 3 4","feedbackType":"1⟲ 2⟲ 3⟲ 4⟲","feedbackAmplitude":14,"feedbackEnvelope":"steady","operators":[{"frequency":"1×","amplitude":12,"envelope":"custom"},{"frequency":"2×","amplitude":15,"envelope":"custom"},{"frequency":"3×","amplitude":12,"envelope":"custom"},{"frequency":"4×","amplitude":15,"envelope":"custom"}]}},
				{name: "fiddle",           midiProgram: 110, generalMidi: true, settings: {"type":"FM","transition":"soft","effects":"reverb","chord":"harmony","filterCutoffHz":2828,"filterResonance":29,"filterEnvelope":"steady","vibrato":"delayed","algorithm":"(1 2)←(3 4)","feedbackType":"3⟲ 4⟲","feedbackAmplitude":5,"feedbackEnvelope":"twang 1","operators":[{"frequency":"2×","amplitude":15,"envelope":"custom"},{"frequency":"8×","amplitude":13,"envelope":"custom"},{"frequency":"1×","amplitude":8,"envelope":"steady"},{"frequency":"16×","amplitude":3,"envelope":"steady"}]}},
			])},
			{name: "Vocals", presets: <DictionaryArray<Preset>> toNameMap([
				{name: "choir ahh",        midiProgram:  52, generalMidi: true, settings: {"type":"harmonics","effects":"chorus & reverb","transition":"soft fade","chord":"harmony","filterCutoffHz":2828,"filterResonance":86,"filterEnvelope":"steady","interval":"union","vibrato":"shaky","harmonics":[86,100,100,86,71,57,29,14,14,14,29,43,43,43,29,14,14,14,0,0,0,0,0,0,0,0,0,0]}},
				{name: "voice ooh",        midiProgram:  53, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"soft","chord":"harmony","filterCutoffHz":1414,"filterResonance":57,"filterEnvelope":"steady","interval":"union","vibrato":"shaky","harmonics":[100,57,43,43,14,14,0,0,0,14,29,29,14,0,14,29,29,14,0,0,0,0,0,0,0,0,0,0]}},
				{name: "synth voice",      midiProgram:  54, generalMidi: true, settings: {"type":"chip","transition":"medium fade","effects":"chorus & reverb","chord":"harmony","filterCutoffHz":4000,"filterResonance":57,"filterEnvelope":"steady","wave":"rounded","interval":"union","vibrato":"light"}},
				{name: "synth vox lead",   midiProgram:  85, generalMidi: true, settings: {"type":"FM","effects":"chorus & reverb","transition":"cross fade","chord":"harmony","filterCutoffHz":2828,"filterResonance":14,"filterEnvelope":"steady","vibrato":"light","algorithm":"(1 2 3)←4","feedbackType":"1→2→3→4","feedbackAmplitude":2,"feedbackEnvelope":"punch","operators":[{"frequency":"2×","amplitude":10,"envelope":"custom"},{"frequency":"9×","amplitude":5,"envelope":"custom"},{"frequency":"20×","amplitude":1,"envelope":"custom"},{"frequency":"~1×","amplitude":4,"envelope":"steady"}]}},
				{name: "halo pad",         midiProgram:  94, generalMidi: true, settings: {"type":"harmonics","effects":"chorus & reverb","transition":"soft fade","chord":"harmony","filterCutoffHz":2828,"filterResonance":43,"filterEnvelope":"swell 2","interval":"union","vibrato":"shaky","harmonics":[86,100,86,43,14,14,57,71,57,14,14,14,14,14,43,57,43,14,14,14,14,14,14,14,0,0,0,0]}},
				{name: "echo drop",        midiProgram: 102, generalMidi: true, settings: {"type":"FM","transition":"hard","effects":"chorus & reverb","chord":"harmony","filterCutoffHz":2000,"filterResonance":14,"filterEnvelope":"punch","vibrato":"none","algorithm":"1←(2 3←4)","feedbackType":"1⟲","feedbackAmplitude":2,"feedbackEnvelope":"steady","operators":[{"frequency":"~2×","amplitude":10,"envelope":"custom"},{"frequency":"~1×","amplitude":5,"envelope":"steady"},{"frequency":"11×","amplitude":2,"envelope":"steady"},{"frequency":"16×","amplitude":5,"envelope":"swell 3"}]}},
				{name: "solo ahh",         midiProgram:  85, settings: {"type":"harmonics","effects":"reverb","transition":"cross fade","chord":"harmony","filterCutoffHz":2828,"filterResonance":29,"filterEnvelope":"swell 1","interval":"union","vibrato":"shaky","harmonics":[86,100,86,43,14,14,57,71,57,14,14,14,14,14,43,57,43,14,14,14,14,14,14,14,0,0,0,0]}},
			])},
			{name: "Brasses", presets: <DictionaryArray<Preset>> toNameMap([
				{name: "trumpet",          midiProgram:  56, generalMidi: true, settings: {"type":"FM","transition":"soft","effects":"reverb","chord":"harmony","filterCutoffHz":2828,"filterResonance":43,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←(2 3 4)","feedbackType":"1⟲","feedbackAmplitude":9,"feedbackEnvelope":"swell 1","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":8,"envelope":"steady"},{"frequency":"1×","amplitude":5,"envelope":"flare 2"},{"frequency":"1×","amplitude":0,"envelope":"steady"}]}},
				{name: "trombone",         midiProgram:  57, generalMidi: true, settings: {"type":"FM","transition":"soft","effects":"reverb","chord":"harmony","filterCutoffHz":2000,"filterResonance":43,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←(2 3 4)","feedbackType":"2⟲","feedbackAmplitude":7,"feedbackEnvelope":"swell 1","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":8,"envelope":"steady"},{"frequency":"1×","amplitude":0,"envelope":"steady"},{"frequency":"1×","amplitude":0,"envelope":"steady"}]}},
				{name: "tuba",             midiProgram:  58, generalMidi: true, settings: {"type":"FM","transition":"soft","effects":"reverb","chord":"harmony","filterCutoffHz":2000,"filterResonance":43,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←(2 3 4)","feedbackType":"2⟲","feedbackAmplitude":8,"feedbackEnvelope":"swell 1","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":6,"envelope":"steady"},{"frequency":"1×","amplitude":0,"envelope":"steady"},{"frequency":"1×","amplitude":0,"envelope":"steady"}]}},
				{name: "muted trumpet",    midiProgram:  59, generalMidi: true, settings: {"type":"FM","transition":"soft","effects":"reverb","chord":"harmony","filterCutoffHz":2828,"filterResonance":14,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←2←3←4","feedbackType":"2⟲","feedbackAmplitude":7,"feedbackEnvelope":"swell 2","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":7,"envelope":"steady"},{"frequency":"5×","amplitude":4,"envelope":"swell 1"},{"frequency":"13×","amplitude":7,"envelope":"swell 2"}]}},
				{name: "french horn",      midiProgram:  60, generalMidi: true, settings: {"type":"FM","transition":"soft","effects":"reverb","chord":"harmony","filterCutoffHz":2828,"filterResonance":14,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←3 2←4","feedbackType":"1⟲ 2⟲","feedbackAmplitude":3,"feedbackEnvelope":"swell 1","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":12,"envelope":"custom"},{"frequency":"1×","amplitude":10,"envelope":"swell 1"},{"frequency":"~1×","amplitude":8,"envelope":"flare 2"}]}},
				{name: "brass section",    midiProgram:  61, generalMidi: true, settings: {"type":"FM","transition":"soft","effects":"reverb","chord":"harmony","filterCutoffHz":2828,"filterResonance":14,"filterEnvelope":"punch","vibrato":"none","algorithm":"1←3 2←4","feedbackType":"1⟲ 2⟲","feedbackAmplitude":6,"feedbackEnvelope":"swell 1","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":13,"envelope":"custom"},{"frequency":"1×","amplitude":10,"envelope":"swell 1"},{"frequency":"~1×","amplitude":10,"envelope":"swell 1"}]}},
				{name: "synth brass 1",    midiProgram:  62, generalMidi: true, settings: {"type":"FM","transition":"soft","effects":"reverb","chord":"harmony","filterCutoffHz":4000,"filterResonance":29,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←3 2←4","feedbackType":"1⟲ 2⟲","feedbackAmplitude":11,"feedbackEnvelope":"swell 1","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":12,"envelope":"flare 1"},{"frequency":"~1×","amplitude":8,"envelope":"flare 2"}]}},
				{name: "synth brass 2",    midiProgram:  63, generalMidi: true, settings: {"type":"FM","transition":"soft","effects":"reverb","chord":"harmony","filterCutoffHz":4000,"filterResonance":43,"filterEnvelope":"twang 3","vibrato":"none","algorithm":"1←3 2←4","feedbackType":"1⟲ 2⟲","feedbackAmplitude":9,"feedbackEnvelope":"swell 1","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":10,"envelope":"flare 1"},{"frequency":"~1×","amplitude":7,"envelope":"flare 1"}]}},
			])},
			{name: "Reeds", presets: <DictionaryArray<Preset>> toNameMap([
				{name: "soprano sax",      midiProgram:  64, generalMidi: true, settings: {"type":"FM","transition":"soft","effects":"reverb","chord":"harmony","filterCutoffHz":2000,"filterResonance":29,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←2←3←4","feedbackType":"4⟲","feedbackAmplitude":5,"feedbackEnvelope":"swell 1","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"4×","amplitude":4,"envelope":"swell 1"},{"frequency":"1×","amplitude":7,"envelope":"steady"},{"frequency":"5×","amplitude":4,"envelope":"punch"}]}},
				{name: "alto sax",         midiProgram:  65, generalMidi: true, settings: {"type":"FM","transition":"soft","effects":"reverb","chord":"harmony","filterCutoffHz":2000,"filterResonance":43,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←(2 3←4)","feedbackType":"1⟲","feedbackAmplitude":4,"feedbackEnvelope":"punch","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":6,"envelope":"steady"},{"frequency":"4×","amplitude":6,"envelope":"swell 1"},{"frequency":"1×","amplitude":12,"envelope":"steady"}]}},
				{name: "tenor sax",        midiProgram:  66, generalMidi: true, settings: {"type":"FM","transition":"soft","effects":"reverb","chord":"harmony","filterCutoffHz":2828,"filterResonance":29,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←2←3←4","feedbackType":"1⟲","feedbackAmplitude":2,"feedbackEnvelope":"swell 1","operators":[{"frequency":"2×","amplitude":15,"envelope":"custom"},{"frequency":"3×","amplitude":7,"envelope":"steady"},{"frequency":"1×","amplitude":3,"envelope":"steady"},{"frequency":"8×","amplitude":2,"envelope":"steady"}]}},
				{name: "baritone sax",     midiProgram:  67, generalMidi: true, settings: {"type":"FM","effects":"reverb","transition":"soft","chord":"harmony","filterCutoffHz":2828,"filterResonance":0,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←(2 3←4)","feedbackType":"1⟲","feedbackAmplitude":2,"feedbackEnvelope":"swell 2","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"8×","amplitude":4,"envelope":"steady"},{"frequency":"4×","amplitude":5,"envelope":"steady"},{"frequency":"1×","amplitude":4,"envelope":"punch"}]}},
				{name: "shehnai",          midiProgram: 111, generalMidi: true, settings: {"type":"FM","transition":"soft","effects":"reverb","chord":"harmony","filterCutoffHz":5657,"filterResonance":14,"filterEnvelope":"punch","vibrato":"delayed","algorithm":"1 2←(3 4)","feedbackType":"2⟲","feedbackAmplitude":4,"feedbackEnvelope":"swell 3","operators":[{"frequency":"4×","amplitude":10,"envelope":"custom"},{"frequency":"3×","amplitude":12,"envelope":"custom"},{"frequency":"1×","amplitude":8,"envelope":"steady"},{"frequency":"7×","amplitude":4,"envelope":"swell 1"}]}},
				{name: "oboe",             midiProgram:  68, generalMidi: true, settings: {"type":"FM","effects":"reverb","transition":"cross fade","chord":"harmony","filterCutoffHz":4000,"filterResonance":14,"filterEnvelope":"swell 1","vibrato":"none","algorithm":"1 2←(3 4)","feedbackType":"2⟲","feedbackAmplitude":2,"feedbackEnvelope":"tremolo5","operators":[{"frequency":"1×","amplitude":9,"envelope":"custom"},{"frequency":"4×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":6,"envelope":"steady"},{"frequency":"6×","amplitude":2,"envelope":"steady"}]}},
				{name: "english horn",     midiProgram:  69, generalMidi: true, settings: {"type":"FM","effects":"reverb","transition":"cross fade","chord":"harmony","filterCutoffHz":2000,"filterResonance":14,"filterEnvelope":"steady","vibrato":"none","algorithm":"1 2←(3 4)","feedbackType":"2⟲","feedbackAmplitude":2,"feedbackEnvelope":"steady","operators":[{"frequency":"4×","amplitude":15,"envelope":"custom"},{"frequency":"2×","amplitude":12,"envelope":"custom"},{"frequency":"1×","amplitude":8,"envelope":"punch"},{"frequency":"8×","amplitude":4,"envelope":"steady"}]}},
				{name: "bassoon",          midiProgram:  70, generalMidi: true, settings: {"type":"FM","transition":"soft","effects":"reverb","chord":"harmony","filterCutoffHz":707,"filterResonance":57,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←(2 3←4)","feedbackType":"1⟲","feedbackAmplitude":2,"feedbackEnvelope":"steady","operators":[{"frequency":"2×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":6,"envelope":"steady"},{"frequency":"6×","amplitude":6,"envelope":"swell 1"},{"frequency":"1×","amplitude":0,"envelope":"steady"}]}},
				{name: "clarinet",         midiProgram:  71, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"soft","chord":"harmony","filterCutoffHz":1414,"filterResonance":14,"filterEnvelope":"steady","interval":"union","vibrato":"none","harmonics":[100,43,86,57,86,71,86,71,71,71,71,71,71,43,71,71,57,57,57,57,57,57,43,43,43,29,14,0]}},
			])},
			{name: "Flutes", presets: <DictionaryArray<Preset>> toNameMap([
				{name: "piccolo",          midiProgram:  72, generalMidi: true, settings: {"type":"FM","transition":"soft","effects":"reverb","chord":"harmony","filterCutoffHz":4000,"filterResonance":14,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←3 2←4","feedbackType":"4⟲","feedbackAmplitude":15,"feedbackEnvelope":"twang 1","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":10,"envelope":"custom"},{"frequency":"~2×","amplitude":3,"envelope":"punch"},{"frequency":"~1×","amplitude":5,"envelope":"punch"}]}},
				{name: "flute",            midiProgram:  73, generalMidi: true, settings: {"type":"FM","effects":"reverb","transition":"soft","chord":"harmony","filterCutoffHz":5657,"filterResonance":14,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←(2 3 4)","feedbackType":"4⟲","feedbackAmplitude":7,"feedbackEnvelope":"decay 2","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"2×","amplitude":4,"envelope":"steady"},{"frequency":"1×","amplitude":3,"envelope":"steady"},{"frequency":"~1×","amplitude":1,"envelope":"punch"}]}},
				{name: "recorder",         midiProgram:  74, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"soft","chord":"harmony","filterCutoffHz":2000,"filterResonance":0,"filterEnvelope":"swell 2","interval":"union","vibrato":"none","harmonics":[100,43,57,43,57,43,43,43,29,29,14,14,14,14,14,14,14,14,14,0,0,0,0,0,0,0,0,0]}},
				{name: "pan flute",        midiProgram:  75, generalMidi: true, settings: {"type":"spectrum","transition":"soft","effects":"reverb","chord":"harmony","filterCutoffHz":8000,"filterResonance":0,"filterEnvelope":"steady","spectrum":[100,0,0,0,0,0,0,14,0,0,0,86,0,0,14,0,71,0,29,14,29,29,14,29,14,29,14,14,29,29]}},
				{name: "blown bottle",     midiProgram:  76, generalMidi: true, settings: {"type":"FM","transition":"cross fade","effects":"chorus & reverb","chord":"harmony","filterCutoffHz":2828,"filterResonance":0,"filterEnvelope":"steady","vibrato":"none","algorithm":"1 2 3 4","feedbackType":"1⟲ 2⟲ 3⟲ 4⟲","feedbackAmplitude":7,"feedbackEnvelope":"twang 1","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"3×","amplitude":3,"envelope":"custom"},{"frequency":"6×","amplitude":1,"envelope":"custom"},{"frequency":"11×","amplitude":1,"envelope":"custom"}]}},
				{name: "shakuhachi",       midiProgram:  77, generalMidi: true, settings: {"type":"FM","effects":"chorus & reverb","transition":"soft","chord":"harmony","filterCutoffHz":2828,"filterResonance":57,"filterEnvelope":"steady","vibrato":"delayed","algorithm":"1←(2 3←4)","feedbackType":"3→4","feedbackAmplitude":15,"feedbackEnvelope":"steady","operators":[{"frequency":"1×","amplitude":12,"envelope":"custom"},{"frequency":"2×","amplitude":3,"envelope":"punch"},{"frequency":"~1×","amplitude":4,"envelope":"twang 1"},{"frequency":"20×","amplitude":15,"envelope":"steady"}]}},
				{name: "whistle",          midiProgram:  78, generalMidi: true, settings: {"type":"harmonics","effects":"chorus & reverb","transition":"soft","chord":"harmony","filterCutoffHz":1414,"filterResonance":0,"filterEnvelope":"steady","interval":"union","vibrato":"delayed","harmonics":[100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},
				{name: "ocarina",          midiProgram:  79, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"soft","chord":"harmony","filterCutoffHz":1414,"filterResonance":0,"filterEnvelope":"steady","interval":"union","vibrato":"none","harmonics":[100,14,43,14,14,14,14,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},
				{name: "calliope",         midiProgram:  82, generalMidi: true, settings: {"type":"spectrum","transition":"cross fade","effects":"reverb","chord":"harmony","filterCutoffHz":5657,"filterResonance":14,"filterEnvelope":"steady","spectrum":[100,0,0,0,0,0,0,86,0,0,0,71,0,0,57,0,43,0,29,14,14,29,14,14,14,14,14,14,14,14]}},
				{name: "chiffer",          midiProgram:  83, generalMidi: true, settings: {"type":"spectrum","transition":"hard","effects":"reverb","chord":"harmony","filterCutoffHz":2000,"filterResonance":14,"filterEnvelope":"punch","spectrum":[100,0,0,0,0,0,0,86,0,0,0,86,0,0,71,0,57,0,43,14,14,43,14,29,14,29,29,29,29,14]}},
				{name: "breath noise",     midiProgram: 121, generalMidi: true, settings: {"type":"spectrum","effects":"reverb","transition":"cross fade","chord":"strum","filterCutoffHz":2000,"filterResonance":14,"filterEnvelope":"twang 1","spectrum":[71,0,0,0,0,0,0,29,0,0,0,71,0,0,29,0,100,29,14,29,100,29,100,14,14,71,0,29,0,0]}},
			])},
			{name: "Pads", presets: <DictionaryArray<Preset>> toNameMap([
				{name: "new age pad",      midiProgram:  88, generalMidi: true, settings: {"type":"FM","effects":"chorus & reverb","transition":"hard fade","chord":"harmony","filterCutoffHz":8000,"filterResonance":43,"filterEnvelope":"twang 3","vibrato":"none","algorithm":"1←(2 3←4)","feedbackType":"1⟲ 2⟲","feedbackAmplitude":3,"feedbackEnvelope":"swell 3","operators":[{"frequency":"2×","amplitude":13,"envelope":"custom"},{"frequency":"~1×","amplitude":4,"envelope":"swell 2"},{"frequency":"6×","amplitude":3,"envelope":"twang 3"},{"frequency":"13×","amplitude":3,"envelope":"steady"}]}},
				{name: "warm pad",         midiProgram:  89, generalMidi: true, settings: {"type":"FM","effects":"chorus & reverb","transition":"soft fade","chord":"harmony","filterCutoffHz":2828,"filterResonance":29,"filterEnvelope":"swell 3","vibrato":"none","algorithm":"1←(2 3 4)","feedbackType":"1⟲","feedbackAmplitude":7,"feedbackEnvelope":"steady","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":6,"envelope":"swell 1"},{"frequency":"1×","amplitude":0,"envelope":"steady"},{"frequency":"1×","amplitude":0,"envelope":"steady"}]}},
				{name: "polysynth pad",    midiProgram:  90, generalMidi: true, settings: {"type":"chip","transition":"hard fade","effects":"chorus & reverb","chord":"harmony","filterCutoffHz":2828,"filterResonance":43,"filterEnvelope":"twang 3","wave":"sawtooth","interval":"hum","vibrato":"delayed"}},
				{name: "space voice pad",  midiProgram:  91, generalMidi: true, settings: {"type":"FM","effects":"chorus & reverb","transition":"medium fade","chord":"harmony","filterCutoffHz":4000,"filterResonance":71,"filterEnvelope":"steady","vibrato":"none","algorithm":"(1 2 3)←4","feedbackType":"1⟲ 2⟲ 3⟲ 4⟲","feedbackAmplitude":5,"feedbackEnvelope":"swell 2","operators":[{"frequency":"1×","amplitude":13,"envelope":"custom"},{"frequency":"2×","amplitude":11,"envelope":"custom"},{"frequency":"3×","amplitude":9,"envelope":"custom"},{"frequency":"11×","amplitude":1,"envelope":"punch"}]}},
				{name: "bowed glass pad",  midiProgram:  92, generalMidi: true, settings: {"type":"FM","effects":"reverb","transition":"soft fade","chord":"harmony","filterCutoffHz":4000,"filterResonance":14,"filterEnvelope":"twang 3","vibrato":"none","algorithm":"1←3 2←4","feedbackType":"1⟲","feedbackAmplitude":0,"feedbackEnvelope":"steady","operators":[{"frequency":"1×","amplitude":9,"envelope":"custom"},{"frequency":"2×","amplitude":12,"envelope":"custom"},{"frequency":"3×","amplitude":7,"envelope":"twang 3"},{"frequency":"7×","amplitude":4,"envelope":"flare 3"}]}},
				{name: "metallic pad",     midiProgram:  93, generalMidi: true, settings: {"type":"FM","effects":"reverb","transition":"medium fade","chord":"harmony","filterCutoffHz":5657,"filterResonance":14,"filterEnvelope":"twang 3","vibrato":"none","algorithm":"1←3 2←4","feedbackType":"1⟲ 2⟲","feedbackAmplitude":13,"feedbackEnvelope":"twang 3","operators":[{"frequency":"1×","amplitude":12,"envelope":"custom"},{"frequency":"~1×","amplitude":7,"envelope":"custom"},{"frequency":"1×","amplitude":7,"envelope":"swell 2"},{"frequency":"11×","amplitude":7,"envelope":"steady"}]}},
				{name: "sweep pad",        midiProgram:  95, generalMidi: true, settings: {"type":"chip","effects":"chorus & reverb","transition":"soft fade","chord":"harmony","filterCutoffHz":4000,"filterResonance":86,"filterEnvelope":"flare 3","wave":"sawtooth","interval":"hum","vibrato":"none"}},
				{name: "atmosphere",       midiProgram:  99, generalMidi: true, settings: {"type":"FM","effects":"chorus & reverb","transition":"hard fade","chord":"strum","filterCutoffHz":4000,"filterResonance":29,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←(2 3 4)","feedbackType":"3⟲ 4⟲","feedbackAmplitude":3,"feedbackEnvelope":"steady","operators":[{"frequency":"1×","amplitude":13,"envelope":"custom"},{"frequency":"1×","amplitude":10,"envelope":"swell 3"},{"frequency":"3×","amplitude":7,"envelope":"twang 2"},{"frequency":"1×","amplitude":7,"envelope":"twang 3"}]}},
				{name: "brightness",       midiProgram: 100, generalMidi: true, settings: {"type":"harmonics","effects":"chorus & reverb","transition":"medium fade","chord":"harmony","filterCutoffHz":2828,"filterResonance":14,"filterEnvelope":"twang 3","interval":"octave","vibrato":"none","harmonics":[100,86,86,86,43,57,43,71,43,43,43,57,43,43,57,71,57,43,29,43,57,57,43,29,29,29,29,14]}},
				{name: "goblins",          midiProgram: 101, generalMidi: true, settings: {"type":"FM","transition":"soft fade","effects":"chorus & reverb","chord":"harmony","filterCutoffHz":1414,"filterResonance":14,"filterEnvelope":"swell 3","vibrato":"none","algorithm":"1←2←3←4","feedbackType":"1⟲","feedbackAmplitude":10,"feedbackEnvelope":"flare 3","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"4×","amplitude":3,"envelope":"swell 3"},{"frequency":"1×","amplitude":10,"envelope":"tremolo1"},{"frequency":"1×","amplitude":0,"envelope":"steady"}]}},
				{name: "sci-fi",           midiProgram: 103, generalMidi: true, settings: {"type":"FM","transition":"medium fade","effects":"chorus & reverb","chord":"harmony","filterCutoffHz":5657,"filterResonance":14,"filterEnvelope":"twang 3","vibrato":"none","algorithm":"(1 2)←3←4","feedbackType":"1⟲ 2⟲ 3⟲ 4⟲","feedbackAmplitude":8,"feedbackEnvelope":"twang 3","operators":[{"frequency":"~1×","amplitude":10,"envelope":"custom"},{"frequency":"2×","amplitude":8,"envelope":"custom"},{"frequency":"5×","amplitude":5,"envelope":"twang 3"},{"frequency":"11×","amplitude":8,"envelope":"tremolo5"}]}},
				{name: "flutter pad",      midiProgram:  90, settings: {"type":"FM","transition":"hard fade","effects":"chorus & reverb","chord":"harmony","filterCutoffHz":4000,"filterResonance":86,"filterEnvelope":"twang 3","vibrato":"delayed","algorithm":"(1 2)←(3 4)","feedbackType":"1⟲ 2⟲ 3⟲","feedbackAmplitude":9,"feedbackEnvelope":"steady","operators":[{"frequency":"1×","amplitude":9,"envelope":"custom"},{"frequency":"5×","amplitude":4,"envelope":"custom"},{"frequency":"7×","amplitude":5,"envelope":"tremolo1"},{"frequency":"~1×","amplitude":6,"envelope":"punch"}]}},
			])},
			{name: "Drums", presets: <DictionaryArray<Preset>> toNameMap([
				{name: "standard drumset", midiProgram: 116, isNoise: true, settings: {"type":"drumset","effects":"reverb","drums":[{"filterEnvelope":"twang 1","spectrum":[57,71,71,86,86,86,71,71,71,71,57,57,57,57,43,43,43,43,29,29,29,29,29,29,29,29,29,29,29,29]},{"filterEnvelope":"twang 1","spectrum":[0,0,0,100,71,71,57,86,57,57,57,71,43,43,57,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43]},{"filterEnvelope":"twang 1","spectrum":[0,0,0,0,100,57,43,43,29,57,43,29,71,43,43,43,43,57,43,43,43,43,43,43,43,43,29,43,43,43]},{"filterEnvelope":"twang 1","spectrum":[0,0,0,0,0,71,57,43,43,43,57,57,43,29,57,43,43,43,29,43,57,43,43,43,43,43,43,29,43,43]},{"filterEnvelope":"decay 2","spectrum":[0,14,29,43,86,71,29,43,43,43,43,29,71,29,71,29,43,43,43,43,57,43,43,57,43,43,43,57,57,57]},{"filterEnvelope":"decay 1","spectrum":[0,0,14,14,14,14,29,29,29,43,43,43,57,57,57,71,71,71,71,71,71,71,71,57,57,57,57,43,43,43]},{"filterEnvelope":"twang 3","spectrum":[43,43,43,71,29,29,43,43,43,29,43,43,43,29,29,43,43,29,29,29,57,14,57,43,43,57,43,43,57,57]},{"filterEnvelope":"decay 3","spectrum":[29,43,43,43,43,29,29,43,29,29,43,29,14,29,43,29,43,29,57,29,43,57,43,71,43,71,57,57,71,71]},{"filterEnvelope":"twang 3","spectrum":[43,29,29,43,29,29,29,57,29,29,29,57,43,43,29,29,57,43,43,43,71,43,43,71,57,71,71,71,71,71]},{"filterEnvelope":"decay 3","spectrum":[57,57,57,43,57,57,43,43,57,43,43,43,71,57,43,57,86,71,57,86,71,57,86,100,71,86,86,86,86,86]},{"filterEnvelope":"flare 1","spectrum":[0,0,14,14,14,14,29,29,29,43,43,43,57,57,71,71,86,86,100,100,100,100,100,100,100,100,86,57,29,0]},{"filterEnvelope":"decay 2","spectrum":[14,14,14,14,29,14,14,29,14,43,14,43,57,86,57,57,100,57,43,43,57,100,57,43,29,14,0,0,0,0]}]}},
				{name: "steel pan",        midiProgram: 114, generalMidi: true, settings: {"type":"FM","transition":"hard fade","effects":"chorus & reverb","chord":"harmony","filterCutoffHz":2828,"filterResonance":0,"filterEnvelope":"decay 2","vibrato":"none","algorithm":"1←(2 3←4)","feedbackType":"4⟲","feedbackAmplitude":0,"feedbackEnvelope":"steady","operators":[{"frequency":"~1×","amplitude":11,"envelope":"custom"},{"frequency":"7×","amplitude":3,"envelope":"flare 1"},{"frequency":"3×","amplitude":5,"envelope":"flare 2"},{"frequency":"4×","amplitude":4,"envelope":"swell 2"}]}},
				{name: "timpani",          midiProgram:  47, generalMidi: true, settings: {"type":"spectrum","transition":"hard fade","effects":"reverb","chord":"harmony","filterCutoffHz":8000,"filterResonance":14,"filterEnvelope":"twang 1","spectrum":[100,0,0,0,86,0,0,57,0,14,43,14,43,43,0,29,43,29,14,14,43,29,43,14,43,43,29,43,29,43]}},
				{name: "woodblock",        midiProgram: 115, generalMidi: true, isNoise: true, settings: {"type":"spectrum","transition":"hard fade","effects":"reverb","chord":"strum","filterCutoffHz":1414,"filterResonance":14,"filterEnvelope":"twang 1","spectrum":[0,0,0,0,0,0,57,71,43,29,29,14,14,29,57,71,14,14,43,29,29,29,29,29,57,71,29,29,29,29]}},
				{name: "taiko drum",       midiProgram: 116, generalMidi: true, isNoise: true, settings: {"type":"spectrum","transition":"hard fade","effects":"reverb","chord":"strum","filterCutoffHz":1000,"filterResonance":14,"filterEnvelope":"twang 1","spectrum":[100,29,29,43,14,29,29,14,29,29,29,14,29,43,29,29,29,14,29,29,14,29,29,29,43,43,29,29,29,29]}},
				{name: "melodic drum",     midiProgram: 117, generalMidi: true, isNoise: true, settings: {"type":"spectrum","transition":"hard fade","effects":"reverb","chord":"strum","filterCutoffHz":2000,"filterResonance":14,"filterEnvelope":"twang 1","spectrum":[100,29,29,57,43,43,43,0,0,0,29,43,29,29,29,0,0,0,0,29,43,29,29,29,29,29,29,29,29,29]}},
				{name: "synth drum",       midiProgram: 118, generalMidi: true, isNoise: true, settings: {"type":"spectrum","effects":"reverb","transition":"hard fade","chord":"strum","filterCutoffHz":8000,"filterResonance":0,"filterEnvelope":"decay 2","spectrum":[100,43,43,43,43,43,43,71,43,43,43,57,43,43,57,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43]}},
			])},
			{name: "Novelty", presets: <DictionaryArray<Preset>> toNameMap([
				{name: "guitar fret noise",midiProgram: 120, generalMidi: true, settings: {"type":"spectrum","effects":"reverb","transition":"hard","chord":"harmony","filterCutoffHz":8000,"filterResonance":86,"filterEnvelope":"flare 1","spectrum":[0,0,0,0,0,0,0,0,0,0,0,0,0,14,0,0,0,29,14,0,0,43,0,43,0,71,43,0,57,0]}},
				{name: "fifth saw lead",   midiProgram:  86, midiSubharmonicOctaves: 1, generalMidi: true, settings: {"type":"chip","effects":"chorus & reverb","transition":"hard fade","chord":"harmony","filterCutoffHz":2828,"filterResonance":57,"filterEnvelope":"twang 3","wave":"sawtooth","interval":"fifth","vibrato":"none"}},
				{name: "soundtrack",       midiProgram:  97, generalMidi: true, settings: {"type":"chip","effects":"chorus & reverb","transition":"soft fade","chord":"harmony","filterCutoffHz":2000,"filterResonance":14,"filterEnvelope":"flare 3","wave":"sawtooth","interval":"fifth","vibrato":"none"}},
				{name: "reverse cymbal",   midiProgram: 119, generalMidi: true, isNoise: true, settings: {"type":"spectrum","transition":"hard","effects":"none","chord":"harmony","filterCutoffHz":2000,"filterResonance":14,"filterEnvelope":"swell 3","spectrum":[14,14,14,29,29,29,29,29,43,29,29,43,43,43,29,29,71,43,86,86,57,100,86,86,86,86,71,86,71,57]}},
				{name: "seashore",         midiProgram: 122, generalMidi: true, isNoise: true, settings: {"type":"spectrum","transition":"soft fade","effects":"reverb","chord":"harmony","filterCutoffHz":2828,"filterResonance":0,"filterEnvelope":"swell 3","spectrum":[14,14,29,29,43,43,43,57,57,57,57,57,57,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,57]}},
				{name: "bird tweet",       midiProgram: 123, generalMidi: true, settings: {"type":"harmonics","effects":"reverb","transition":"soft","chord":"strum","filterCutoffHz":2828,"filterResonance":0,"filterEnvelope":"decay 1","interval":"hum","vibrato":"heavy","harmonics":[0,0,14,100,14,0,0,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},
				{name: "telephone ring",   midiProgram: 124, generalMidi: true, settings: {"type":"FM","transition":"hard","effects":"reverb","chord":"arpeggio","filterCutoffHz":4000,"filterResonance":14,"filterEnvelope":"tremolo4","vibrato":"none","algorithm":"1←(2 3 4)","feedbackType":"1⟲","feedbackAmplitude":2,"feedbackEnvelope":"steady","operators":[{"frequency":"2×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":4,"envelope":"tremolo1"},{"frequency":"20×","amplitude":1,"envelope":"steady"},{"frequency":"1×","amplitude":0,"envelope":"steady"}]}},
				{name: "helicopter",       midiProgram: 125, generalMidi: true, isNoise: true, settings: {"type":"spectrum","transition":"soft","effects":"reverb","chord":"harmony","filterCutoffHz":2828,"filterResonance":0,"filterEnvelope":"tremolo1","spectrum":[100,57,100,57,57,57,100,100,100,100,43,0,100,100,100,100,100,57,100,100,100,100,100,100,86,86,86,71,71,71]}},
				{name: "applause",         midiProgram: 126, generalMidi: true, isNoise: true, settings: {"type":"spectrum","transition":"soft fade","effects":"reverb","chord":"harmony","filterCutoffHz":707,"filterResonance":0,"filterEnvelope":"swell 3","spectrum":[29,29,29,43,43,29,29,29,43,57,86,86,86,71,71,57,57,57,71,71,86,86,86,86,71,71,71,57,57,43]}},
				{name: "gunshot",          midiProgram: 127, generalMidi: true, isNoise: true, settings: {"type":"spectrum","transition":"hard fade","effects":"reverb","chord":"strum","filterCutoffHz":1414,"filterResonance":29,"filterEnvelope":"twang 1","spectrum":[14,29,29,29,43,43,43,57,57,57,71,71,71,71,71,71,71,71,71,71,71,57,57,57,57,43,43,43,43,29]}},
				{name: "buzz saw",         midiProgram:  30, settings: {"type":"FM","effects":"reverb","transition":"soft","chord":"custom interval","filterCutoffHz":2000,"filterResonance":0,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←2←3←4","feedbackType":"1⟲","feedbackAmplitude":0,"feedbackEnvelope":"steady","operators":[{"frequency":"5×","amplitude":13,"envelope":"custom"},{"frequency":"1×","amplitude":10,"envelope":"steady"},{"frequency":"~1×","amplitude":6,"envelope":"steady"},{"frequency":"11×","amplitude":12,"envelope":"steady"}]}},
			])},
			{name: "Unclassified Program", presets: <DictionaryArray<Preset>> toNameMap([
				{name: "FM twang",         midiProgram:  81, settings: {"type":"FM","transition":"hard","effects":"none","chord":"custom interval","filterCutoffHz":8000,"filterResonance":0,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←(2 3 4)","feedbackType":"1⟲","feedbackAmplitude":0,"feedbackEnvelope":"steady","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":15,"envelope":"twang 2"},{"frequency":"1×","amplitude":0,"envelope":"steady"},{"frequency":"1×","amplitude":0,"envelope":"steady"}]}},
				{name: "FM bass",          midiProgram:  81, settings: {"type":"FM","effects":"reverb","transition":"hard","chord":"strum","filterCutoffHz":8000,"filterResonance":0,"filterEnvelope":"steady","vibrato":"none","algorithm":"1←(2 3 4)","feedbackType":"1⟲","feedbackAmplitude":0,"feedbackEnvelope":"steady","operators":[{"frequency":"1×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":9,"envelope":"steady"},{"frequency":"16×","amplitude":6,"envelope":"twang 1"},{"frequency":"1×","amplitude":0,"envelope":"steady"}]}},
				{name: "FM bell",          midiProgram:  14, settings: {"type":"FM","transition":"hard fade","effects":"reverb","chord":"strum","filterCutoffHz":2000,"filterResonance":29,"filterEnvelope":"twang 3","vibrato":"none","algorithm":"1←(2 3 4)","feedbackType":"1⟲","feedbackAmplitude":0,"feedbackEnvelope":"steady","operators":[{"frequency":"~2×","amplitude":15,"envelope":"custom"},{"frequency":"7×","amplitude":6,"envelope":"twang 3"},{"frequency":"20×","amplitude":1,"envelope":"twang 1"},{"frequency":"1×","amplitude":0,"envelope":"steady"}]}},
				{name: "tiny robot",       midiProgram:  81, settings: {"type":"FM","transition":"slide","effects":"reverb","chord":"harmony","filterCutoffHz":8000,"filterResonance":0,"filterEnvelope":"steady","vibrato":"delayed","algorithm":"1←(2 3 4)","feedbackType":"1⟲","feedbackAmplitude":2,"feedbackEnvelope":"twang 3","operators":[{"frequency":"2×","amplitude":15,"envelope":"custom"},{"frequency":"1×","amplitude":7,"envelope":"punch"},{"frequency":"~1×","amplitude":7,"envelope":"steady"},{"frequency":"1×","amplitude":0,"envelope":"steady"}]}},
				{name: "yowie",            midiProgram:  81, settings: {"type":"FM","transition":"cross fade","effects":"reverb","chord":"harmony","filterCutoffHz":2000,"filterResonance":86,"filterEnvelope":"tremolo5","vibrato":"none","algorithm":"1←2←(3 4)","feedbackType":"1⟲","feedbackAmplitude":12,"feedbackEnvelope":"tremolo3","operators":[{"frequency":"2×","amplitude":10,"envelope":"custom"},{"frequency":"16×","amplitude":5,"envelope":"steady"},{"frequency":"1×","amplitude":5,"envelope":"steady"},{"frequency":"1×","amplitude":0,"envelope":"steady"}]}},
				{name: "alt synthstrings?",midiProgram:  81, settings: {"type":"FM","transition":"soft fade","effects":"chorus & reverb","chord":"harmony","filterCutoffHz":2000,"filterResonance":0,"filterEnvelope":"steady","vibrato":"none","algorithm":"1 2 3 4","feedbackType":"1→2→3→4","feedbackAmplitude":11,"feedbackEnvelope":"steady","operators":[{"frequency":"1×","amplitude":10,"envelope":"custom"},{"frequency":"~2×","amplitude":11,"envelope":"steady"},{"frequency":"4×","amplitude":10,"envelope":"steady"},{"frequency":"7×","amplitude":8,"envelope":"steady"}]}},
				{name: "synth scoot",      midiProgram:  81, settings: {"type":"chip","transition":"hard","effects":"reverb","chord":"harmony","filterCutoffHz":707,"filterResonance":86,"filterEnvelope":"flare 1","wave":"sawtooth","interval":"shimmer","vibrato":"none"}},
				{name: "spectrum choir",   midiProgram:  81, settings: {"type":"spectrum","transition":"soft fade","effects":"chorus & reverb","chord":"harmony","filterCutoffHz":2828,"filterResonance":43,"filterEnvelope":"swell 2","spectrum":[100,0,0,0,0,0,0,100,0,0,0,100,0,0,71,0,29,0,0,0,0,0,0,14,0,29,14,0,57,14]}},
				{name: "tom-tom",          midiProgram: 117, isNoise: true, settings: {"type":"spectrum","effects":"reverb","transition":"hard fade","chord":"strum","filterCutoffHz":2000,"filterResonance":14,"filterEnvelope":"twang 1","spectrum":[100,29,14,0,0,86,14,43,29,86,29,14,29,57,43,43,43,43,57,43,43,43,29,57,43,43,43,43,43,43]}},
				{name: "gong",             midiProgram: 119, isNoise: true, settings: {"type":"spectrum","transition":"hard fade","effects":"reverb","chord":"harmony","filterCutoffHz":4000,"filterResonance":14,"filterEnvelope":"swell 1","spectrum":[100,29,43,29,43,14,14,14,14,29,14,43,29,43,43,43,43,43,43,43,29,29,29,29,29,29,29,29,14,14]}},
				{name: "retro drum",       midiProgram: 119, isNoise: true, settings: {"type":"noise","transition":"hard","effects":"none","chord":"arpeggio","filterCutoffHz":4000,"filterResonance":0,"filterEnvelope":"steady","wave":"retro"}},
				{name: "pipe organ2",      midiProgram:  19, midiSubharmonicOctaves: 1, settings: {"type":"harmonics","effects":"reverb","transition":"cross fade","chord":"harmony","filterCutoffHz":4000,"filterResonance":29,"filterEnvelope":"steady","interval":"hum","vibrato":"none","harmonics":[86,100,71,100,57,71,57,100,43,57,43,86,43,57,43,100,29,57,29,86,29,57,29,86,29,43,29,43]}},
				{name: "soprano sax2",     midiProgram:  64, settings: {"type":"harmonics","effects":"reverb","transition":"soft","chord":"harmony","filterCutoffHz":2828,"filterResonance":0,"filterEnvelope":"punch","interval":"union","vibrato":"none","harmonics":[100,86,86,43,86,86,71,43,57,57,57,57,43,29,43,43,43,43,29,29,29,29,29,29,29,14,14,14]}},
				{name: "alto sax2",        midiProgram:  65, settings: {"type":"harmonics","effects":"reverb","transition":"soft","chord":"harmony","filterCutoffHz":2828,"filterResonance":0,"filterEnvelope":"punch","interval":"union","vibrato":"none","harmonics":[86,86,71,86,71,57,57,71,57,57,57,57,57,57,57,57,57,43,43,43,43,43,43,29,29,29,29,14]}},
				{name: "tenor sax2",       midiProgram:  66, settings: {"type":"harmonics","effects":"reverb","transition":"soft","chord":"harmony","filterCutoffHz":1414,"filterResonance":0,"filterEnvelope":"punch","interval":"union","vibrato":"none","harmonics":[71,71,71,71,86,71,57,57,71,71,71,71,71,57,57,71,71,71,71,71,71,57,57,57,43,43,43,29]}},
				{name: "baritone sax2",    midiProgram:  67, settings: {"type":"harmonics","effects":"reverb","transition":"soft","chord":"harmony","filterCutoffHz":2000,"filterResonance":14,"filterEnvelope":"punch","interval":"union","vibrato":"none","harmonics":[57,86,71,57,71,71,86,86,71,43,71,71,86,71,57,57,57,71,71,71,57,43,57,57,57,57,43,43]}},
			])},
		]);
		
		public static readonly pitchColors: DictionaryArray<ChannelColors> = toNameMap([
			{name: "cyan",   channelDim: "#0099a1", channelBright: "#25f3ff", noteDim: "#00bdc7", noteBright: "#92f9ff"},
			{name: "yellow", channelDim: "#a1a100", channelBright: "#ffff25", noteDim: "#c7c700", noteBright: "#ffff92"},
			{name: "orange", channelDim: "#c75000", channelBright: "#ff9752", noteDim: "#ff771c", noteBright: "#ffcdab"},
			{name: "green",  channelDim: "#00a100", channelBright: "#50ff50", noteDim: "#00c700", noteBright: "#a0ffa0"},
			{name: "purple", channelDim: "#d020d0", channelBright: "#ff90ff", noteDim: "#e040e0", noteBright: "#ffc0ff"},
			{name: "blue",   channelDim: "#7777b0", channelBright: "#a0a0ff", noteDim: "#8888d0", noteBright: "#d0d0ff"},
		]);
		public static readonly noiseColors: DictionaryArray<ChannelColors> = toNameMap([
			{name: "gray",   channelDim: "#6f6f6f", channelBright: "#aaaaaa", noteDim: "#a7a7a7", noteBright: "#e0e0e0"},
			{name: "brown",  channelDim: "#996633", channelBright: "#ddaa77", noteDim: "#cc9966", noteBright: "#f0d0bb"},
			{name: "azure",  channelDim: "#4a6d8f", channelBright: "#77aadd", noteDim: "#6f9fcf", noteBright: "#bbd7ff"},
		]);
		
		public static valueToPreset(presetValue: number): Preset | null {
			const categoryIndex: number = presetValue >> 6;
			const presetIndex: number = presetValue & 0x3F;
			return EditorConfig.presetCategories[categoryIndex].presets[presetIndex];
		}
		
		public static midiProgramToPresetValue(program: number): number | null {
			for (let categoryIndex: number = 0; categoryIndex < EditorConfig.presetCategories.length; categoryIndex++) {
				const category: PresetCategory = EditorConfig.presetCategories[categoryIndex];
				for (let presetIndex: number = 0; presetIndex < category.presets.length; presetIndex++) {
					const preset: Preset = category.presets[presetIndex];
					if (preset.generalMidi && preset.midiProgram == program) return (categoryIndex << 6) + presetIndex;
				}
			}
			return null;
		}
		
		public static nameToPresetValue(presetName: string): number | null {
			for (let categoryIndex: number = 0; categoryIndex < EditorConfig.presetCategories.length; categoryIndex++) {
				const category: PresetCategory = EditorConfig.presetCategories[categoryIndex];
				for (let presetIndex: number = 0; presetIndex < category.presets.length; presetIndex++) {
					const preset: Preset = category.presets[presetIndex];
					if (preset.name == presetName) return (categoryIndex << 6) + presetIndex;
				}
			}
			return null;
		}
	}
}